<?php
session_start();
// In installer/stage4.php - REPLACE the config generation section

$db = $_SESSION['db_config'] ?? [];

// === Generate config/app.php ===
$config_content = "<?php\n";
$config_content .= "// Auto-generated config — DO NOT EDIT MANUALLY\n";
$config_content .= "return [\n";
$config_content .= "    'database' => [\n";
$config_content .= "        'host'     => '" . addslashes($db['host']) . "',\n";
$config_content .= "        'name'     => '" . addslashes($db['name']) . "',\n";
$config_content .= "        'user'     => '" . addslashes($db['user']) . "',\n";
$config_content .= "        'pass'     => '" . addslashes($db['pass']) . "',\n";
$config_content .= "        'prefix'   => '" . addslashes($db['prefix']) . "',\n";
$config_content .= "        'charset'  => 'utf8mb4',\n";
$config_content .= "    ],\n";
$config_content .= "    'installed' => true,\n";
$config_content .= "    'install_date' => '" . date('Y-m-d H:i:s') . "',\n";
$config_content .= "];\n";

// Write config/app.php
$config_path = __DIR__ . '/../config/app.php';
if (file_put_contents($config_path, $config_content) === false) {
    die("<h2 style='color:red;'>❌ Failed to write config file.</h2>");
}

// === Generate .env file ===
$dotenv_content = "# Auto-generated by VTU Installer on " . date('Y-m-d H:i:s') . "\n";
$dotenv_content .= "# DO NOT commit to version control\n\n";

// Database
$dotenv_content .= "DB_HOST=" . $db['host'] . "\n";
$dotenv_content .= "DB_NAME=" . $db['name'] . "\n";
$dotenv_content .= "DB_USER=" . $db['user'] . "\n";
$dotenv_content .= "DB_PASS=" . $db['pass'] . "\n";
$dotenv_content .= "DB_PREFIX=" . $db['prefix'] . "\n\n";

// Security
$dotenv_content .= "MIN_PIN_LENGTH=4\n";
$dotenv_content .= "PIN_ATTEMPTS_LIMIT=3\n";
$dotenv_content .= "SESSION_TIMEOUT=3600\n";
$dotenv_content .= "CSP_ENABLED=false\n";
$dotenv_content .= "HSTS_ENABLED=false\n\n";

// Webhooks
$dotenv_content .= "WEBHOOK_SECRET=" . bin2hex(random_bytes(32)) . "\n\n";

// Application
$dotenv_content .= "APP_DEBUG=false\n";
$dotenv_content .= "APP_TIMEZONE=Africa/Lagos\n";

// Write .env
$dotenv_path = __DIR__ . '/../.env';
if (file_put_contents($dotenv_path, $dotenv_content) !== false) {
    @chmod($dotenv_path, 0600); // Secure permissions
    $env_created = true;
} else {
    $env_created = false;
}

// === Finalize Installation ===
// Create a .installed lock file to prevent re-running the installer
file_put_contents(__DIR__ . '/.installed', 'Installation completed on ' . date('Y-m-d H:i:s'));

// Clear the session to allow for a fresh start if needed
session_destroy();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VTU Installer — Installation Complete</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&display=swap" rel="stylesheet">
    <style>
        :root { --primary: #4361ee; --success: #06d6a0; --warning: #ffd166; --danger: #ef476f; }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Inter', sans-serif; background: #f5f7fb; color: #333; padding: 1.5rem; }
        .container { max-width: 700px; margin: 0 auto; }
        .card { background: white; border-radius: 16px; box-shadow: 0 10px 25px rgba(0,0,0,0.08); overflow: hidden; text-align: center; }
        .header { background: var(--success); color: white; padding: 2rem; }
        .header h2 { font-weight: 600; font-size: 1.8rem; }
        .content { padding: 2.5rem; }
        .btn { display: inline-block; margin-top: 1.5rem; background: var(--primary); color: white; padding: 0.8rem 1.5rem; text-decoration: none; border-radius: 10px; font-weight: 600; }
        .security-note { margin-top: 2rem; padding: 1rem; background: #fff8e6; border-radius: 8px; border-left: 4px solid #ffd166; }
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="header">
                <h2>✅ Installation Complete!</h2>
            </div>
            <div class="content">
                <p>Congratulations! Your new VTU site is ready.</p>
                <a href="../admin/" class="btn">Go to Admin Login</a>
                <div class="security-note">
                    <h3>🔐 Security Recommendations:</h3>
                    <ul style="text-align: left; padding-left: 1.5rem; margin-top: 0.5rem;">
                        <li>Go to <strong>Admin Dashboard → API Manager</strong> and enter your MTN, Flutterwave, and Paystack keys</li>
                        <li>Set up email (SMTP) in <strong>Settings → Email</strong></li>
                        <?php if ($env_created): ?>
                        <li>✅ <code>.env</code> file created with secure defaults</li>
                        <li>🔒 Run: <code>chmod 600 .env</code> to secure it</li>
                        <?php else: ?>
                        <li>⚠️ Failed to create <code>.env</code> — create manually from <code>.env.example</code></li>
                        <?php endif; ?>
                        <li>🚫 Delete the <code>/installer/</code> folder for security</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
